"""
ig_caption.py - Instagram caption generator.

Captions are generated by Gemini flash-lite, the sole caption provider. Claude
was retired 2026-06-22 and is never used here. System prompt enforces project
voice rules: show-don't-tell, arrive-late-leave-early, no em dashes,
niche-first hashtag stack, 50-130 words, single CTA. Post-process regex checks
bounce captions that violate the rules; up to 3 retries before marking the row
state='caption_review' for manual edit.

Usage:
    python -m pipeline.social.ig_caption                       # all draft captionable
    python -m pipeline.social.ig_caption --post-id <uuid>      # one row

Environment:
    GEMINI_API_KEY      required for caption generation (flash-lite)
    SUPABASE_URL / KEY  existing pipeline vars
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from utils.supabase_client import supabase  # noqa: E402

try:
    from summarizer import gemini_client
except ImportError:
    gemini_client = None  # type: ignore

# ---------------------------------------------------------------------------
# Voice rules (mirrors CLAUDE.md project rules)
# ---------------------------------------------------------------------------

BANNED_PHRASES = [
    "notable", "notably",
    "significant", "significantly",
    "interesting", "interestingly",
    "it should be noted",
    "it is worth noting",
    "crucial", "crucially",
    "in conclusion",
    "to sum up",
    "in summary",
    "in essence",
    "needless to say",
]

EM_DASH_RE = re.compile(r"[—–]")
HASHTAG_RE = re.compile(r"#[A-Za-z0-9_]{2,}")
URL_RE = re.compile(r"https?://\S+|news\.voidvision\.org")

IG_MAX_CAPTION_CHARS = 2200
WORD_MIN = 50
WORD_MAX = 130

# Approved hashtag stack. The caption LLM picks 6-8 from here.
HASHTAG_POOL = {
    "niche": [
        "medialiteracy", "newsmediabias", "algorithmaccountability",
        "datajournalism", "computationaljournalism", "explanatoryjournalism",
        "pressfreedom", "factchecking",
    ],
    "domain": [
        "journalism", "worldnews", "independentmedia",
        "publicinterest", "newsanalysis",
    ],
    "owned": [
        "voidnews", "seethroughthevoid",
    ],
}

SYSTEM_PROMPT = """You write Instagram captions for Void News.

Void News is a news aggregator that prints one daily front page: the same 50 stories, in the same order, for everyone, ranked once a day by how widely each story is covered, not by clicks. Every article carries a bias score traced to specific words. No accounts, no tracking, free forever. It has sister products: Void History (consequential events told from every side) and Void Weekly (the week read like a magazine).

Voice rules, enforced, not aspirational:

1. SHOW, DON'T TELL. Never use the words notable, notably, significant, significantly, interesting, interestingly, crucial, crucially, "it should be noted", "it is worth noting", "in conclusion", "in summary", "needless to say". Use concrete numbers, named outlets, named people, dates, places, verbs.

2. ARRIVE LATE, LEAVE EARLY. Open in the middle of the action. End before the conclusion is spelled out. The reader completes the thought.

3. NO EM DASHES OR EN DASHES. Hyphens in compound words like "fact-check" are fine. Use two short sentences, a comma, a semicolon, a colon, or parentheses instead.

4. LENGTH: 50 to 130 words. One CTA at the end if useful. URL goes at the very end, no preamble.

5. HASHTAGS: pick 6 to 8 from the approved stack provided in the user message. Place them at the very end on a new line. No hashtags inside the body.

6. MANIFESTO: the Void News promise is "Same stories. Same order. For everyone." Every caption ladders up to it. Quote the line verbatim at most once per week, usually paraphrase.

7. NEVER write "void --news" or "void --history"; the brands are "Void News" and "Void History". The site is "news.voidvision.org".

8. NEVER praise the product. Never say "we built something amazing." Let the evidence carry the weight.

Output STRICT JSON with this shape:
{
  "caption": "the caption body, no hashtags inside",
  "hashtags": ["medialiteracy", "newsmediabias", ...]
}

The body must end with the URL "news.voidvision.org" unless the post type indicates otherwise."""


def _build_user_prompt(row: dict[str, Any]) -> str:
    pillar = row.get("pillar", "vision")
    specs = row.get("slide_specs") or []
    spec_summary = json.dumps(specs[:4], indent=2)[:2000]

    if pillar == "vision":
        intent = (
            "VISION post (manifesto, emotional). The three slides are a provocation about "
            "the algorithmic feed, the core principle, and a sign-off. Write from conviction: "
            "what the personalized feed quietly did to a shared set of facts, and why one front "
            "page for everyone is the answer. Paraphrase the manifesto (quote it verbatim at most "
            "once a week). Land on the idea that the order of the news should not be tuned to you. "
            "End with the URL."
        )
    elif pillar == "method":
        intent = (
            "METHOD post (credibility, we show the math). The slides demonstrate one of the six "
            "bias axes on a real sample sentence, with a score. Explain how that axis is measured "
            "from the words themselves, rule by rule, not from who published it. Contrast implicitly "
            "with label-the-outlet rating sites: every Void score traces to specific words. Name the "
            "axis. End on a first principle, not a feature. URL last."
        )
    elif pillar == "example":
        intent = (
            "EXAMPLE post (today's real story across outlets, the proof). The slides plot several "
            "named outlets covering ONE real event on a left-to-right lean axis. Lead with the "
            "divergence: name two outlets at opposite ends and quote or paraphrase how their framing "
            "differs. Do not editorialize about who is right. Land on per-article, not per-outlet, "
            "without using that phrase verbatim. Use the outlet names and scores from the slides. URL last."
        )
    elif pillar == "history":
        intent = (
            "HISTORY post (archival, multi-perspective) for Void History. Drop the reader inside one "
            "fact about the event on the slides, then note that the record holds several accounts with "
            "no winner declared. Do not lecture. Let the fact and the competing voices carry it. "
            "End with the news.voidvision.org/history URL."
        )
    elif pillar == "weekly":
        intent = (
            "WEEKLY post (the week in review) for Void Weekly. The slides carry the issue's cover "
            "headline, deck, and the week's key or most-contested stories. Caption is a short standfirst: "
            "name the issue number, tease two of the stories by their real headlines, and point to the "
            "edition. Three sentences of context, no more. End with the news.voidvision.org/weekly URL."
        )
    else:
        intent = "Standard Void News post. Follow the voice rules. URL last."

    pool = (
        "niche: " + ", ".join(HASHTAG_POOL["niche"]) + "\n"
        "domain: " + ", ".join(HASHTAG_POOL["domain"]) + "\n"
        "owned: " + ", ".join(HASHTAG_POOL["owned"])
    )

    return f"""POST PILLAR: {pillar}
POST INTENT: {intent}

SLIDE CONTENT (first 4 slides, JSON):
{spec_summary}

APPROVED HASHTAG POOL (lead with niche; include at least 1 owned):
{pool}

Write the caption now. Return STRICT JSON only."""


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------

def _validate(caption: str, hashtags: list[str]) -> tuple[bool, str]:
    if not caption or not isinstance(caption, str):
        return False, "empty caption"
    if EM_DASH_RE.search(caption):
        return False, "contains em/en dash"

    lower = caption.lower()
    for banned in BANNED_PHRASES:
        if banned in lower:
            return False, f"banned phrase: {banned}"

    word_count = len(re.findall(r"\b\w+\b", caption))
    if word_count < WORD_MIN:
        return False, f"too short ({word_count} words, min {WORD_MIN})"
    if word_count > WORD_MAX:
        return False, f"too long ({word_count} words, max {WORD_MAX})"

    if HASHTAG_RE.search(caption):
        return False, "hashtags inside caption body (must be on separate line)"

    if not isinstance(hashtags, list) or len(hashtags) < 6 or len(hashtags) > 8:
        return False, f"wrong hashtag count ({len(hashtags) if isinstance(hashtags, list) else 'n/a'}; need 6-8)"

    all_allowed = set(HASHTAG_POOL["niche"] + HASHTAG_POOL["domain"] + HASHTAG_POOL["owned"])
    cleaned = [h.lstrip("#").strip() for h in hashtags]
    for h in cleaned:
        if h not in all_allowed:
            return False, f"hashtag not in approved stack: {h}"

    total_len = len(caption) + sum(len(h) + 2 for h in cleaned)
    if total_len > IG_MAX_CAPTION_CHARS:
        return False, f"total length exceeds IG limit ({total_len} > {IG_MAX_CAPTION_CHARS})"

    return True, "ok"


# ---------------------------------------------------------------------------
# Generation
# ---------------------------------------------------------------------------

def _llm_available() -> bool:
    """True if Gemini flash-lite is usable. Claude is never used for captions
    (retired 2026-06-22); flash-lite is the sole provider."""
    return gemini_client is not None and gemini_client.is_available()


def _generate_caption_json(prompt: str) -> dict | None:
    """Generate one caption via Gemini flash-lite - the sole caption provider.
    Claude is never used (retired 2026-06-22). flash-lite keeps captions off the
    flash 20/day budget the main pipeline's brief + top-10 already spend."""
    if gemini_client is None or not gemini_client.is_available():
        return None
    return gemini_client.generate_json(
        prompt=prompt,
        system_instruction=SYSTEM_PROMPT,
        max_retries=0,  # we handle retries ourselves so we can adjust prompt
        count_call=True,
        max_output_tokens=2048,
        model=gemini_client._MODEL,  # flash-lite - never flash, never Claude
    )


def caption_for_post(row: dict[str, Any], max_retries: int = 3) -> tuple[str | None, list[str] | None, str | None]:
    """Returns (caption, hashtags, error). Error is None on success."""
    if not _llm_available():
        return None, None, "no caption LLM available (set GEMINI_API_KEY)"

    prompt = _build_user_prompt(row)

    last_err = "unknown"
    for attempt in range(max_retries):
        result = _generate_caption_json(prompt)
        if not result:
            last_err = "LLM returned no JSON"
            continue

        caption_raw = (result.get("caption") or "").strip()
        hashtags_raw = result.get("hashtags") or []
        if isinstance(hashtags_raw, str):
            hashtags_raw = [h.strip() for h in re.split(r"[,\s]+", hashtags_raw) if h.strip()]
        hashtags = [h.lstrip("#").strip() for h in hashtags_raw if isinstance(h, str)]

        ok, msg = _validate(caption_raw, hashtags)
        if ok:
            return caption_raw, hashtags, None

        last_err = msg
        # Tighten prompt for next try
        prompt = (
            _build_user_prompt(row)
            + f"\n\nPREVIOUS ATTEMPT FAILED: {msg}. Fix it. Return STRICT JSON only."
        )

    return None, None, last_err


def _set_state(post_id: str, state: str, error: str | None = None) -> None:
    payload: dict[str, Any] = {"state": state}
    if error is not None:
        payload["error"] = error[:1000]
    try:
        supabase.table("ig_posts").update(payload).eq("id", post_id).execute()
    except Exception as e:
        print(f"  [error] state update {post_id} → {state}: {e}")


def _write_caption(post_id: str, caption: str, hashtags: list[str]) -> None:
    try:
        supabase.table("ig_posts").update({
            "caption": caption,
            "hashtags": hashtags,
        }).eq("id", post_id).execute()
    except Exception as e:
        print(f"  [error] caption write {post_id}: {e}")


def _fetch_targets(post_id: str | None) -> list[dict]:
    q = supabase.table("ig_posts").select("id, slide_specs, pillar, caption, state")
    if post_id:
        q = q.eq("id", post_id)
    else:
        # Caption rows that have rendered images but no caption yet.
        q = q.in_("state", ["draft"]).is_("caption", "null")
    return (q.order("scheduled_for", desc=False).limit(50).execute().data) or []


def caption_all(post_id: str | None = None) -> int:
    rows = _fetch_targets(post_id)
    if not rows:
        print("  [caption] nothing to do")
        return 0

    done = 0
    for row in rows:
        pid = row["id"]
        _set_state(pid, "captioning")
        cap, tags, err = caption_for_post(row)
        if cap and tags is not None:
            _write_caption(pid, cap, tags)
            # leave state at 'draft' so the admin picks it up; the captioning
            # state is a transient lock so concurrent runs don't collide
            _set_state(pid, "draft")
            print(f"  [caption] {pid} ok ({len(cap)} chars, {len(tags)} tags)")
            done += 1
        else:
            _set_state(pid, "caption_review", err or "validation failed")
            print(f"  [caption] {pid} → caption_review: {err}")
    return done


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--post-id", default=None, help="caption a single post")
    args = parser.parse_args()
    n = caption_all(post_id=args.post_id)
    print(f"  [caption] done. {n} caption(s) written.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
