"""
ig_caption.py - Instagram caption generator (+ per-platform variants + intent).

Captions are generated by Gemini flash-lite, the sole caption provider. Claude
was retired 2026-06-22 and is never used here. System prompt enforces project
voice rules: show-don't-tell, arrive-late-leave-early, no em dashes,
niche-first hashtag stack, 50-130 words, single CTA. Post-process regex checks
bounce captions that violate the rules; up to 3 retries before marking the row
state='caption_review' for manual edit.

The SAME single Gemini call now also returns three extra fields (2026-08-05,
manual-upload pivot; migration 074):
  caption_x        X/Twitter variant, <= 280 chars, at most 1-2 hashtags
  caption_bluesky  Bluesky variant, <= 300 chars, plain (no hashtag wall)
  intent           one-sentence director's note (the emotion/message the post
                   is going for), a cue for the CEO's personal touch at upload.
No extra API call: the variants + intent ride inside the existing JSON output.
Every variant is passed through the same voice rules (no em/en dashes, banned
phrases). If the model omits a variant, X/Bluesky are DERIVED by trimming the
IG caption and intent falls back to a neutral note, rather than failing the row.
ig_export.py reads all of these into the downloadable manual-upload bundle.

Usage:
    python -m pipeline.social.ig_caption                       # all draft captionable
    python -m pipeline.social.ig_caption --post-id <uuid>      # one row

Environment:
    GEMINI_API_KEY      required for caption generation (flash-lite)
    SUPABASE_URL / KEY  existing pipeline vars
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from utils.supabase_client import supabase  # noqa: E402

try:
    from summarizer import gemini_client
except ImportError:
    gemini_client = None  # type: ignore

# ---------------------------------------------------------------------------
# Voice rules (mirrors CLAUDE.md project rules)
# ---------------------------------------------------------------------------

BANNED_PHRASES = [
    "notable", "notably",
    "significant", "significantly",
    "interesting", "interestingly",
    "it should be noted",
    "it is worth noting",
    "crucial", "crucially",
    "in conclusion",
    "to sum up",
    "in summary",
    "in essence",
    "needless to say",
]

EM_DASH_RE = re.compile(r"[—–]")
HASHTAG_RE = re.compile(r"#[A-Za-z0-9_]{2,}")
URL_RE = re.compile(r"https?://\S+|news\.voidvision\.org")

IG_MAX_CAPTION_CHARS = 2200
WORD_MIN = 50
WORD_MAX = 130

# Per-platform hard character ceilings (2026-08-05).
X_MAX_CHARS = 280
BLUESKY_MAX_CHARS = 300

NEUTRAL_INTENT = (
    "Inform without alarm: let the facts and named outlets carry the weight, "
    "then point the reader to the front page."
)

# Approved hashtag stack. The caption LLM picks 6-8 from here.
HASHTAG_POOL = {
    "niche": [
        "medialiteracy", "newsmediabias", "algorithmaccountability",
        "datajournalism", "computationaljournalism", "explanatoryjournalism",
        "pressfreedom", "factchecking",
    ],
    "domain": [
        "journalism", "worldnews", "independentmedia",
        "publicinterest", "newsanalysis",
    ],
    "owned": [
        "voidnews", "seethroughthevoid",
    ],
}

SYSTEM_PROMPT = """You write Instagram captions for Void News.

Void News is a news aggregator that prints one daily front page: the same 50 stories, in the same order, for everyone, ranked once a day by how widely each story is covered, not by clicks. Every article carries a bias score traced to specific words. No accounts, no tracking, free forever. It has sister products: Void History (consequential events told from every side) and Void Weekly (the week read like a magazine).

Voice rules, enforced, not aspirational:

1. SHOW, DON'T TELL. Never use the words notable, notably, significant, significantly, interesting, interestingly, crucial, crucially, "it should be noted", "it is worth noting", "in conclusion", "in summary", "needless to say". Use concrete numbers, named outlets, named people, dates, places, verbs.

2. ARRIVE LATE, LEAVE EARLY. Open in the middle of the action. End before the conclusion is spelled out. The reader completes the thought.

3. NO EM DASHES OR EN DASHES. Hyphens in compound words like "fact-check" are fine. Use two short sentences, a comma, a semicolon, a colon, or parentheses instead.

4. LENGTH: 50 to 130 words. One CTA at the end if useful. URL goes at the very end, no preamble.

5. HASHTAGS: pick 6 to 8 from the approved stack provided in the user message. Place them at the very end on a new line. No hashtags inside the body.

6. MANIFESTO: the Void News promise is "Same stories. Same order. For everyone." Every caption ladders up to it. Quote the line verbatim at most once per week, usually paraphrase.

7. NEVER write "void --news" or "void --history"; the brands are "Void News" and "Void History". The site is "news.voidvision.org".

8. NEVER praise the product. Never say "we built something amazing." Let the evidence carry the weight.

9. PER-PLATFORM VARIANTS. Besides the Instagram caption, write two shorter variants of the SAME message. Rules 1-3 (show-don't-tell, arrive-late-leave-early, no em/en dashes) apply to every variant.
   - caption_x: the X/Twitter version, 280 characters or fewer INCLUDING any hashtags. At most 1 or 2 hashtags, from the approved stack. Keep the URL. Tighten, do not just truncate.
   - caption_bluesky: the Bluesky version, 300 characters or fewer. Plain prose, no hashtag wall (zero hashtags is fine, one at most). Keep the URL.

10. INTENT. One sentence, a director's note naming the emotion or message the post is going for, written to the editor (not the audience). Example: "Quiet alarm, not outrage: let the two numbers do the work." Rules 1-3 apply. Do not restate the caption.

Output STRICT JSON with this shape:
{
  "caption": "the Instagram caption body, no hashtags inside",
  "hashtags": ["medialiteracy", "newsmediabias", ...],
  "caption_x": "the X variant, <= 280 chars incl. up to 1-2 hashtags",
  "caption_bluesky": "the Bluesky variant, <= 300 chars, plain, no hashtag wall",
  "intent": "one-sentence director's note on the emotion/message"
}

The Instagram caption body must end with the URL "news.voidvision.org" unless the post type indicates otherwise."""


def _operator_note() -> str:
    """Optional free-text steer for THIS batch, dispatched via the workflow's
    `note` input and threaded in as SOCIAL_NOTE. Empty/unset -> no steer, so the
    prompt is byte-for-byte identical to the pre-steer behavior."""
    return (os.environ.get("SOCIAL_NOTE") or "").strip()


def _operator_steer_block(note: str) -> str:
    """The operator steer, injected into the caption prompt. Shapes angle /
    emphasis / emotional register only; never authorizes new facts, never
    relaxes a voice rule. Empty note -> empty string (no prompt change)."""
    if not note:
        return ""
    return (
        "\n\nOPERATOR STEER (from the editor, for THIS batch only):\n"
        f"\"{note}\"\n"
        "Let this steer shape the ANGLE, the EMPHASIS, and the EMOTIONAL REGISTER "
        "of the Instagram caption AND every variant (X, Bluesky), and make the "
        "intent line visibly reflect this direction so the editor can see it was "
        "heard. The steer changes tone and emphasis ONLY. It does NOT license any "
        "new fact: every fact must still come from the SLIDE CONTENT above. Keep "
        "obeying every rule already stated (show-don't-tell, arrive-late-leave-"
        "early, no em or en dashes, the length and character limits, the hashtag "
        "stack, and the banned phrases)."
    )


def _build_user_prompt(row: dict[str, Any]) -> str:
    pillar = row.get("pillar", "vision")
    specs = row.get("slide_specs") or []
    spec_summary = json.dumps(specs[:4], indent=2)[:2000]

    if pillar == "vision":
        intent = (
            "VISION post (manifesto, emotional). The three slides are a provocation about "
            "the algorithmic feed, the core principle, and a sign-off. Write from conviction: "
            "what the personalized feed quietly did to a shared set of facts, and why one front "
            "page for everyone is the answer. Paraphrase the manifesto (quote it verbatim at most "
            "once a week). Land on the idea that the order of the news should not be tuned to you. "
            "End with the URL."
        )
    elif pillar == "method":
        intent = (
            "METHOD post (credibility, we show the math). The slides demonstrate one of the six "
            "bias axes on a real sample sentence, with a score. Explain how that axis is measured "
            "from the words themselves, rule by rule, not from who published it. Contrast implicitly "
            "with label-the-outlet rating sites: every Void score traces to specific words. Name the "
            "axis. End on a first principle, not a feature. URL last."
        )
    elif pillar == "example":
        intent = (
            "EXAMPLE post (today's real story across outlets, the proof). The slides plot several "
            "named outlets covering ONE real event on a left-to-right lean axis. Lead with the "
            "divergence: name two outlets at opposite ends and quote or paraphrase how their framing "
            "differs. Do not editorialize about who is right. Land on per-article, not per-outlet, "
            "without using that phrase verbatim. Use the outlet names and scores from the slides. URL last."
        )
    elif pillar == "history":
        intent = (
            "HISTORY post (archival, multi-perspective) for Void History. Drop the reader inside one "
            "fact about the event on the slides, then note that the record holds several accounts with "
            "no winner declared. Do not lecture. Let the fact and the competing voices carry it. "
            "End with the news.voidvision.org/history URL."
        )
    elif pillar == "weekly":
        intent = (
            "WEEKLY post (the week in review) for Void Weekly. The slides carry the issue's cover "
            "headline, deck, and the week's key or most-contested stories. Caption is a short standfirst: "
            "name the issue number, tease two of the stories by their real headlines, and point to the "
            "edition. Three sentences of context, no more. End with the news.voidvision.org/weekly URL."
        )
    else:
        intent = "Standard Void News post. Follow the voice rules. URL last."

    pool = (
        "niche: " + ", ".join(HASHTAG_POOL["niche"]) + "\n"
        "domain: " + ", ".join(HASHTAG_POOL["domain"]) + "\n"
        "owned: " + ", ".join(HASHTAG_POOL["owned"])
    )

    steer = _operator_steer_block(_operator_note())

    return f"""POST PILLAR: {pillar}
POST INTENT: {intent}

SLIDE CONTENT (first 4 slides, JSON):
{spec_summary}

APPROVED HASHTAG POOL (lead with niche; include at least 1 owned):
{pool}{steer}

Write the caption now. Return STRICT JSON only."""


# ---------------------------------------------------------------------------
# Variant sanitizing (X / Bluesky / intent)
#
# Variants are NOT retry drivers (a bad variant never burns the caption's
# retry budget). They are sanitized and length-clamped post-validation; a
# missing/dirty variant is DERIVED from the already-clean IG caption so a row
# never fails over a variant. This mirrors the "fail-fast, fall back" policy.
# ---------------------------------------------------------------------------

def _strip_dashes(text: str) -> str:
    """Replace banned em/en dashes with grammatical punctuation. A best-effort
    sanitizer for internal preview copy the CEO will edit; ' — ' becomes ', '
    and a bare dash is dropped, then whitespace/commas are collapsed."""
    if not text:
        return ""
    text = re.sub(r"\s*[—–]\s*", ", ", text)
    text = re.sub(r"\s{2,}", " ", text)
    text = re.sub(r"(,\s*){2,}", ", ", text)
    return text.strip().strip(",").strip()


def _has_banned(text: str) -> bool:
    lower = (text or "").lower()
    return any(b in lower for b in BANNED_PHRASES)


def _strip_body(caption: str) -> str:
    """The IG caption body with any trailing hashtag line removed (hashtags
    only ever live on the final line per rule 5)."""
    lines = [ln for ln in (caption or "").splitlines()]
    while lines and (not lines[-1].strip() or HASHTAG_RE.search(lines[-1])):
        lines.pop()
    return "\n".join(lines).strip() or (caption or "").strip()


def _trim_to(text: str, limit: int) -> str:
    """Sentence-aware trim to <= limit chars. Prefer a sentence boundary, then
    a word boundary, then a hard cut. No ellipsis (keeps the char budget honest)."""
    text = (text or "").strip()
    if len(text) <= limit:
        return text
    window = text[:limit]
    # Prefer the last sentence end within the window.
    m = list(re.finditer(r"[.!?](\s|$)", window))
    if m and m[-1].end() >= int(limit * 0.5):
        return window[: m[-1].start() + 1].strip()
    # Else fall back to the last whitespace.
    cut = window.rfind(" ")
    if cut >= int(limit * 0.5):
        return window[:cut].strip()
    return window.strip()


def _derive_variant_from_caption(caption: str, limit: int) -> str:
    """Fallback variant: strip hashtags + dashes off the IG caption, keep the
    trailing URL if it fits, and trim to `limit` chars."""
    body = _strip_dashes(_strip_body(caption))
    url_match = URL_RE.search(body)
    url = url_match.group(0) if url_match else ""
    if url:
        body = body[: url_match.start()].strip()
    if url and (len(body) + 1 + len(url)) > limit:
        # Trim the body to leave room for a space + URL.
        body = _trim_to(body, max(0, limit - len(url) - 1)).rstrip(" .,")
    trimmed = f"{body} {url}".strip() if url else _trim_to(body, limit)
    return _trim_to(trimmed, limit)


def _finalize_variant(raw: Any, caption: str, limit: int) -> str:
    """Sanitize a model-supplied variant; derive from the clean IG caption if
    it is missing, over-limit after sanitizing, or contains a banned phrase."""
    text = _strip_dashes(raw if isinstance(raw, str) else "")
    if not text or _has_banned(text):
        return _derive_variant_from_caption(caption, limit)
    if len(text) > limit:
        text = _trim_to(text, limit)
    # A trim can still leave it clean; only re-derive if trimming emptied it.
    return text or _derive_variant_from_caption(caption, limit)


def _finalize_intent(raw: Any) -> str:
    text = _strip_dashes(raw if isinstance(raw, str) else "")
    if not text or _has_banned(text) or len(text) < 8:
        return NEUTRAL_INTENT
    # Keep it to a single sentence, capped for a director's note.
    return _trim_to(text, 240)


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------

def _validate(caption: str, hashtags: list[str]) -> tuple[bool, str]:
    if not caption or not isinstance(caption, str):
        return False, "empty caption"
    if EM_DASH_RE.search(caption):
        return False, "contains em/en dash"

    lower = caption.lower()
    for banned in BANNED_PHRASES:
        if banned in lower:
            return False, f"banned phrase: {banned}"

    word_count = len(re.findall(r"\b\w+\b", caption))
    if word_count < WORD_MIN:
        return False, f"too short ({word_count} words, min {WORD_MIN})"
    if word_count > WORD_MAX:
        return False, f"too long ({word_count} words, max {WORD_MAX})"

    if HASHTAG_RE.search(caption):
        return False, "hashtags inside caption body (must be on separate line)"

    if not isinstance(hashtags, list) or len(hashtags) < 6 or len(hashtags) > 8:
        return False, f"wrong hashtag count ({len(hashtags) if isinstance(hashtags, list) else 'n/a'}; need 6-8)"

    all_allowed = set(HASHTAG_POOL["niche"] + HASHTAG_POOL["domain"] + HASHTAG_POOL["owned"])
    cleaned = [h.lstrip("#").strip() for h in hashtags]
    for h in cleaned:
        if h not in all_allowed:
            return False, f"hashtag not in approved stack: {h}"

    total_len = len(caption) + sum(len(h) + 2 for h in cleaned)
    if total_len > IG_MAX_CAPTION_CHARS:
        return False, f"total length exceeds IG limit ({total_len} > {IG_MAX_CAPTION_CHARS})"

    return True, "ok"


# ---------------------------------------------------------------------------
# Generation
# ---------------------------------------------------------------------------

def _llm_available() -> bool:
    """True if Gemini flash-lite is usable. Claude is never used for captions
    (retired 2026-06-22); flash-lite is the sole provider."""
    return gemini_client is not None and gemini_client.is_available()


def _generate_caption_json(prompt: str) -> dict | None:
    """Generate one caption via Gemini flash-lite - the sole caption provider.
    Claude is never used (retired 2026-06-22). flash-lite keeps captions off the
    flash 20/day budget the main pipeline's brief + top-10 already spend."""
    if gemini_client is None or not gemini_client.is_available():
        return None
    return gemini_client.generate_json(
        prompt=prompt,
        system_instruction=SYSTEM_PROMPT,
        max_retries=0,  # we handle retries ourselves so we can adjust prompt
        count_call=True,
        max_output_tokens=2048,
        model=gemini_client._MODEL,  # flash-lite - never flash, never Claude
    )


def caption_for_post(row: dict[str, Any], max_retries: int = 3) -> tuple[dict | None, str | None]:
    """Generate the IG caption + X/Bluesky variants + intent from one call.

    Returns (result, error). On success `error` is None and `result` is a dict:
        {caption, hashtags, caption_x, caption_bluesky, intent}
    Only the IG caption + hashtags gate the retry loop; the variants + intent
    are sanitized / derived from the clean caption and never fail the row."""
    if not _llm_available():
        return None, "no caption LLM available (set GEMINI_API_KEY)"

    prompt = _build_user_prompt(row)

    last_err = "unknown"
    for attempt in range(max_retries):
        result = _generate_caption_json(prompt)
        if not result:
            last_err = "LLM returned no JSON"
            continue

        caption_raw = (result.get("caption") or "").strip()
        hashtags_raw = result.get("hashtags") or []
        if isinstance(hashtags_raw, str):
            hashtags_raw = [h.strip() for h in re.split(r"[,\s]+", hashtags_raw) if h.strip()]
        hashtags = [h.lstrip("#").strip() for h in hashtags_raw if isinstance(h, str)]

        ok, msg = _validate(caption_raw, hashtags)
        if ok:
            return {
                "caption": caption_raw,
                "hashtags": hashtags,
                "caption_x": _finalize_variant(result.get("caption_x"), caption_raw, X_MAX_CHARS),
                "caption_bluesky": _finalize_variant(
                    result.get("caption_bluesky"), caption_raw, BLUESKY_MAX_CHARS
                ),
                "intent": _finalize_intent(result.get("intent")),
            }, None

        last_err = msg
        # Tighten prompt for next try
        prompt = (
            _build_user_prompt(row)
            + f"\n\nPREVIOUS ATTEMPT FAILED: {msg}. Fix it. Return STRICT JSON only."
        )

    return None, last_err


def _set_state(post_id: str, state: str, error: str | None = None) -> None:
    payload: dict[str, Any] = {"state": state}
    if error is not None:
        payload["error"] = error[:1000]
    try:
        supabase.table("ig_posts").update(payload).eq("id", post_id).execute()
    except Exception as e:
        print(f"  [error] state update {post_id} → {state}: {e}")


def _write_caption(post_id: str, result: dict) -> None:
    payload = {
        "caption": result["caption"],
        "hashtags": result["hashtags"],
        "caption_x": result.get("caption_x"),
        "caption_bluesky": result.get("caption_bluesky"),
        "intent": result.get("intent"),
    }
    try:
        supabase.table("ig_posts").update(payload).eq("id", post_id).execute()
    except Exception as e:
        # Migration 074 may not be applied yet; retry with the legacy columns
        # only so the caption still lands and the row is not lost.
        msg = str(e).lower()
        if "caption_x" in msg or "caption_bluesky" in msg or "intent" in msg or "column" in msg:
            print(f"  [warn] caption variant columns missing (apply migration 074): {e}")
            try:
                supabase.table("ig_posts").update({
                    "caption": result["caption"],
                    "hashtags": result["hashtags"],
                }).eq("id", post_id).execute()
                return
            except Exception as e2:
                print(f"  [error] caption write {post_id} (legacy fallback): {e2}")
                return
        print(f"  [error] caption write {post_id}: {e}")


def _fetch_targets(post_id: str | None) -> list[dict]:
    q = supabase.table("ig_posts").select("id, slide_specs, pillar, caption, state")
    if post_id:
        q = q.eq("id", post_id)
    else:
        # Caption rows that have rendered images but no caption yet.
        q = q.in_("state", ["draft"]).is_("caption", "null")
    return (q.order("scheduled_for", desc=False).limit(50).execute().data) or []


def caption_all(post_id: str | None = None) -> int:
    rows = _fetch_targets(post_id)
    if not rows:
        print("  [caption] nothing to do")
        return 0

    done = 0
    for row in rows:
        pid = row["id"]
        _set_state(pid, "captioning")
        result, err = caption_for_post(row)
        if result:
            _write_caption(pid, result)
            # leave state at 'draft' so the admin picks it up; the captioning
            # state is a transient lock so concurrent runs don't collide
            _set_state(pid, "draft")
            print(
                f"  [caption] {pid} ok ({len(result['caption'])} chars, "
                f"{len(result['hashtags'])} tags, x={len(result['caption_x'])}c, "
                f"bsky={len(result['caption_bluesky'])}c)"
            )
            done += 1
        else:
            _set_state(pid, "caption_review", err or "validation failed")
            print(f"  [caption] {pid} → caption_review: {err}")
    return done


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--post-id", default=None, help="caption a single post")
    args = parser.parse_args()
    n = caption_all(post_id=args.post_id)
    print(f"  [caption] done. {n} caption(s) written.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
