/* void --revolt — Nepal Gen Z + India Cockroach Janta Party (added later). */
import type { Revolution } from './types';

export const MOCK_ACTIVE_EXTRA_2: Revolution[] = [
  {
    id: "nepal-gen-z",
    slug: "nepal-gen-z",
    title: "Nepal's Gen Z Uprising",
    subtitle: "A ban on 26 social media platforms lit four days that ended K.P. Sharma Oli's government and made a former chief justice the country's first woman prime minister",
    era: "square-revolutions",
    region: "south-asia",
    country: "Nepal",
    revoltType: "democratic-uprising",
    status: "consolidating",
    dateDisplay: "2025 to present",
    dateStart: 2025,
    summary:
      "On 4 September 2025 Nepal's government blocked 26 social media platforms, including Facebook, YouTube, X, WhatsApp and Instagram, for failing to register with the communications ministry. The ban arrived on top of an online 'nepo kids' trend contrasting the lifestyles of politicians' families with youth unemployment and corruption. On 8 September tens of thousands, most of them young, gathered at Maitighar Mandala and outside the federal parliament in Kathmandu; police used tear gas, water cannon and live ammunition, and at least 19 people were killed that day. The government lifted the ban the same evening. On 9 September protesters set fire to the parliament, the Singha Durbar administrative complex, the Supreme Court and the residences of the president and prime minister, and Prime Minister K.P. Sharma Oli resigned. The army chief announced the military would take charge of security. On 12 September former chief justice Sushila Karki was sworn in as interim prime minister, the first woman to head Nepal's government, after an online consultation among protesters on a Discord server; parliament was dissolved and elections were scheduled for 5 March 2026. That vote was held on schedule; the Rastriya Swatantra Party won a parliamentary majority and Kathmandu mayor Balendra Shah was sworn in as prime minister on 27 March 2026, replacing the interim government.",
    significance:
      "Nepal is a case in which a leaderless, online-coordinated youth movement toppled a durable political figure in roughly four days, and then used an open Discord channel rather than a party to help choose the interim leader who replaced him. It tests whether a mobilization organized without a single spokesperson can convert a rapid collapse into durable institutional reform. At the March 2026 election voters replaced the incumbent coalition with a newer party rather than returning the same actors, leaving open whether that turnover delivers the reform the movement demanded.",
    analyticalOutlook:
      "Nepal held the scheduled election on 5 March 2026. The Rastriya Swatantra Party, which Kathmandu mayor Balendra Shah joined in December 2025, won 182 of 275 lower-house seats, and Shah was sworn in as prime minister on 27 March 2026, replacing Sushila Karki's interim government. The comparative record suggests the period after a leader falls, not the fall itself, is when transitions are most often recaptured by the institutions that survive them, and the harder test now is whether a new governing party can reform the electoral and anti-corruption machinery while the established parties, their local networks and much of the bureaucracy remain in place. Placement on the arc: the old government collapsed, a scheduled election produced a change of governing party rather than a return of the incumbents, and whether that turnover translates into durable institutional reform is not yet settled.",
    grievances: [
      { kind: "corruption", intensity: 88, evidence: "Protests coalesced around an online 'nepo kids' trend contrasting the wealth and lifestyles of politicians' relatives with everyday hardship, in a country ranked in the lower half of Transparency International's corruption index and governed by a rotating set of the same party leaders for most of the post-2008 republic." },
      { kind: "employment", intensity: 80, evidence: "Youth unemployment was reported near 20 percent and hundreds of thousands of young Nepalis leave each year for work abroad; remittances account for a large share of national income, and grievances centered on the gap between elite privilege and youth prospects." },
      { kind: "civil-liberties", intensity: 82, evidence: "The immediate trigger was a 4 September 2025 order blocking 26 social media platforms for failing to register locally, cutting off both political expression and online livelihoods; the ban was lifted on 8 September after the first day of deadly clashes." },
    ],
    repressionLevel: "severe",
    actors: [
      { actorType: "students-youth", name: "Gen Z protesters", description: "A largely leaderless network of young Nepalis who organized over TikTok, Instagram, Discord and other platforms, with logistical support from the youth NGO Hami Nepal, deliberately avoiding a single spokesperson.", roleInArc: "Set the timing, messaging and demands of the uprising and, after Oli's fall, used an open Discord consultation to advocate for an interim leader rather than negotiating through a party.", defected: false },
      { actorType: "masses", name: "Cross-class Kathmandu crowds", description: "Tens of thousands who joined the online-organized calls at Maitighar Mandala and the parliament, widening after the first day's killings.", roleInArc: "Provided the numbers that overwhelmed the security cordon on 8 and 9 September.", defected: false },
      { actorType: "security-forces", name: "Nepal Police", description: "Civilian police deployed to defend the parliament and government complexes.", roleInArc: "Used tear gas, water cannon, rubber bullets and live ammunition on 8 September, killing protesters and making the crackdown, not the ban, the movement's central grievance.", defected: false },
      { actorType: "military", name: "The Nepali Army", description: "The armed forces under Chief of Army Staff Ashok Raj Sigdel.", roleInArc: "Declined to fight for Oli, announced on 9 September that it would take charge of security, secured the streets and airport, and helped broker the transition to an interim government.", defected: true },
      { actorType: "old-regime", name: "K.P. Sharma Oli and his government", description: "Oli, a veteran leader of the Communist Party of Nepal (Unified Marxist-Leninist) heading a coalition, whose cabinet ordered the social media ban.", roleInArc: "Ordered the ban and the crackdown, then resigned on 9 September as the army withdrew active backing and government buildings burned.", defected: false },
    ],
    tactics: [
      { tacticType: "mass-demonstration", description: "Rallies that began peacefully at Maitighar Mandala and outside the federal parliament before escalating into confrontation with security forces.", prominence: "high" },
      { tacticType: "digital-mobilization", description: "Coordination over TikTok, Instagram and Discord, including a large Discord consultation that protesters used to argue for an interim leader after Oli's resignation.", prominence: "high" },
      { tacticType: "occupation", description: "On 9 September crowds stormed and, in several cases, set fire to the parliament, the Singha Durbar administrative complex, the Supreme Court and the residences of senior officials, the property destruction that made the uprising a hybrid rather than a purely nonviolent one.", prominence: "high" },
    ],
    resistanceType: "hybrid",
    phases: [
      { phase: "old-regime-crisis", label: "Nepo kids and a stalled republic", dateStart: "2025-08", tStart: 0.00, tEnd: 0.12, intensity: 35, reached: true, summary: "An online 'nepo kids' trend crystallizes years of frustration with corruption, youth unemployment and a small set of party leaders who have rotated through power since the 2008 republic.", keyEvents: ["Spread of the 'nepo kids' social media trend", "Rising anger over youth unemployment and outward migration"] },
      { phase: "the-spark", label: "The ban and the first day's dead", dateStart: "2025-09-04", tStart: 0.22, tEnd: 0.34, intensity: 72, reached: true, summary: "The government blocks 26 social media platforms on 4 September. On 8 September tens of thousands rally in Kathmandu; police open fire and at least 19 people are killed. The ban is lifted that evening and the home minister resigns.", keyEvents: ["Social media ban on 26 platforms, 4 September 2025", "Deadly clashes at the parliament, 8 September 2025", "Ban lifted and home minister Ramesh Lekhak resigns"] },
      { phase: "radical-phase", label: "Buildings burn and Oli falls", dateStart: "2025-09-09", tStart: 0.60, tEnd: 0.72, intensity: 92, reached: true, summary: "Crowds set fire to the parliament, Singha Durbar, the Supreme Court and officials' residences. K.P. Sharma Oli resigns and is moved to an army barracks; the army chief announces the military will take charge of security.", keyEvents: ["Arson at parliament and Singha Durbar, 9 September 2025", "K.P. Sharma Oli resigns", "Army chief Ashok Raj Sigdel announces the military is taking charge"] },
      { phase: "consolidation", label: "An interim government, a March vote, a new majority", dateStart: "2025-09-12", tStart: 0.92, tEnd: 1.00, intensity: 58, reached: true, summary: "After an online consultation among protesters on Discord and talks with the president and army, former chief justice Sushila Karki is sworn in on 12 September as interim prime minister, the first woman to head Nepal's government. Parliament is dissolved and elections are set for 5 March 2026. The vote is held on schedule; the Rastriya Swatantra Party wins a parliamentary majority and Kathmandu mayor Balendra Shah is sworn in as prime minister on 27 March 2026.", keyEvents: ["Sushila Karki sworn in as interim prime minister, 12 September 2025", "Parliament dissolved", "General election held, 5 March 2026", "Rastriya Swatantra Party wins a majority; Balendra Shah sworn in as prime minister, 27 March 2026"] },
    ],
    outcome: "ongoing-unresolved",
    peakParticipationPct: null,
    peakParticipationDisplay: "Tens of thousands filled central Kathmandu on 8 and 9 September, with parallel protests in other towns; no verified figure exists for peak participation as a share of Nepal's roughly 30 million people.",
    crossedParticipationThreshold: null,
    militaryDefection: "partial",
    foreignIntervention: "none",
    deathToll: "At least 72 people were killed in the September 2025 unrest, a toll several official and press counts put close to 76. The Nepali Army's official account attributed 22 protester deaths, 3 police and 10 prisoners shot during a mass jailbreak to gunfire; the remainder include people who died in the fires set on 9 September. More than 2,000 people were injured.",
    deathTollLow: 72,
    deathTollHigh: 76,
    regimeBefore: "democracy",
    regimeAfter: "unresolved",
    democratizationDelta: null,
    successFactors: [
      { factorKey: "resistance_method", label: "Method of struggle", framework: "chenoweth", status: "Hybrid. A mass, largely nonviolent mobilization that escalated on 9 September into arson and destruction of government buildings, alongside police live fire against protesters.", direction: "indeterminate", baseRate: "About 53 percent of nonviolent campaigns from 1900 to 2006 succeeded, versus about 26 percent for armed ones.", rationale: "The movement kept its favorable odds while it stayed a mass protest, but the turn to property destruction introduces the kind of violence that can narrow participation and hand the state a security rationale.", sources: ["Chenoweth and Stephan, Why Civil Resistance Works (2011)"], asOf: "2025", confidence: "medium" },
      { factorKey: "peak_participation", label: "Peak participation", framework: "chenoweth", status: "Large and cross-class in Kathmandu, but no reliable estimate exists for peak share of the national population.", direction: "indeterminate", baseRate: "No nonviolent campaign that mobilized at least 3.5 percent of the population at its peak has failed to achieve its stated aim, in the dataset built through 2006.", rationale: "Crowds were large enough to overwhelm the capital's security cordon, but the 3.5 percent threshold has not been independently verified for this case and the movement was not consistently nonviolent.", sources: ["Chenoweth and Stephan, Why Civil Resistance Works (2011)"], asOf: "2025", confidence: "low" },
      { factorKey: "security_defection", label: "Did the security forces defect", framework: "chenoweth", status: "Partial. The police carried out the lethal crackdown, but the army declined to fight for Oli, took charge of security and helped broker his exit and the interim government.", direction: "favors-movement", baseRate: "Defection of the security forces is the single strongest predictor of a nonviolent campaign's success.", rationale: "The split within the state, police repression but an army unwilling to sustain it, is what let the government fall within days rather than settle into a prolonged standoff.", sources: ["Nepstad, Nonviolent Revolutions (2011)"], asOf: "2025", confidence: "high" },
      { factorKey: "elite_fracture", label: "Did the ruling bloc fracture", framework: "goldstone", status: "Decisive in the short term. The home minister and then the prime minister resigned, parliament was dissolved, and the governing coalition collapsed within four days.", direction: "favors-movement", baseRate: "Revolutions and forced political openings rarely succeed until the ruling elite itself fractures or loses cohesion.", rationale: "The government's rapid disintegration, rather than protest numbers alone, produced the opening the movement then had to fill.", sources: ["Goldstone, Revolution and Rebellion in the Early Modern World (1991)"], asOf: "2025", confidence: "high" },
      { factorKey: "transition_capture", label: "Surviving the transition", framework: "skocpol", status: "In progress. The March 2026 election was held on schedule; the Rastriya Swatantra Party won a parliamentary majority and Balendra Shah replaced Karki's interim government on 27 March 2026, while the established parties, their local networks and the bureaucracy remain in place.", direction: "indeterminate", baseRate: "Revolutions are most fragile in the period after the ruler falls, when the old state's institutions survive and can reassert themselves.", rationale: "The election changed the party in power rather than returning the incumbents; whether the new government changes the underlying system or is blunted by the institutions that survived the uprising will show whether the movement reformed the state or only replaced its leadership.", sources: ["Skocpol, States and Social Revolutions (1979)"], asOf: "2026", confidence: "medium" },
    ],
    keyFigures: [
      { name: "K.P. Sharma Oli", role: "Prime Minister until his resignation on 9 September 2025", born: 1952, wikipedia: "https://en.wikipedia.org/wiki/K._P._Sharma_Oli" },
      { name: "Sushila Karki", role: "Former Chief Justice of the Supreme Court, sworn in on 12 September 2025 as interim prime minister and the first woman to head Nepal's government", born: 1952, wikipedia: "https://en.wikipedia.org/wiki/Sushila_Karki" },
      { name: "Ashok Raj Sigdel", role: "Chief of Army Staff, who announced the military would take charge of security and helped broker the transition", wikipedia: "https://en.wikipedia.org/wiki/Ashok_Raj_Sigdel" },
      { name: "Ram Chandra Poudel", role: "President, who appointed Karki, dissolved parliament and set elections for March 2026", born: 1944, wikipedia: "https://en.wikipedia.org/wiki/Ram_Chandra_Poudel" },
      { name: "Balen Shah", role: "Mayor of Kathmandu, discussed among protesters as a possible interim leader; he joined the Rastriya Swatantra Party in December 2025, led it to a parliamentary majority in the March 2026 election, and was sworn in as prime minister on 27 March 2026", born: 1990, wikipedia: "https://en.wikipedia.org/wiki/Balendra_Shah" },
    ],
    legacyPoints: [
      "Ended the government of K.P. Sharma Oli, one of Nepal's most durable political figures, in roughly four days, over a social media ban that became a referendum on corruption and youth prospects.",
      "Put the first woman, former chief justice Sushila Karki, at the head of Nepal's government, chosen with input from an open online consultation rather than a party.",
      "At the March 2026 election voters gave the Rastriya Swatantra Party a parliamentary majority and made Kathmandu mayor Balendra Shah prime minister, replacing the established coalition rather than returning it; whether the new government delivers the anti-corruption and institutional reform the movement demanded remains unresolved.",
    ],
    perspectives: [
      { id: "np-movement", viewpoint: "The Gen Z protesters", viewpointType: "movement", regionOrigin: "Kathmandu", narrative: "They cut off the platforms we live and speak on, then answered our rally with live rounds. The ban was the last insult from a class that lets its own children live abroad in comfort while ours line up for visas. We did not want to burn anything. We wanted the people who did this gone, and we wanted a say in who came next.", keyArguments: ["The killings on 8 September, not the ban alone, made Oli's resignation the only acceptable outcome.", "A leaderless movement can still shape the succession when it organizes the choice in the open."], emphasized: ["The first day's deaths", "Corruption and the 'nepo kids' divide"], omitted: ["The arson's cost and who bears responsibility for it"], notableQuotes: [] },
      { id: "np-academic", viewpoint: "The analyst", viewpointType: "academic", regionOrigin: "Global", narrative: "Nepal fell in days because the army chose not to fight for a government the police were already dying to defend. That split inside the state is the same variable that decided Dhaka in 2024 and Manila in 1986. It explains the speed of the collapse; it does not tell you what a newly elected government does with the mandate the election handed it.", keyArguments: ["A divided security apparatus, not protest size alone, explains how fast the government fell.", "The harder test is whether the government elected in March 2026 reforms the party system or is absorbed by it."], emphasized: ["Comparative base rates", "The transition period"], omitted: [], notableQuotes: [] },
    ],
    connections: [
      { targetSlug: "bangladesh-july-revolution", targetTitle: "Bangladesh's July Revolution", type: "parallel", description: "Both are South Asian youth uprisings that toppled a long-serving leader within days after a specific grievance met a lethal crackdown, and both left an unelected interim government, Muhammad Yunus in Dhaka and Sushila Karki in Kathmandu, to reform institutions and organize an election." },
      { targetSlug: "kenya-gen-z", targetTitle: "Kenya's Gen Z Uprising", type: "shared-repertoire", description: "Both were organized online with little visible party or union leadership by a generation with no single spokesperson to arrest, and both forced a rapid government concession, though Kenya's president kept power while Nepal's did not." },
    ],
    media: [],
    relatedRevoltSlugs: ["bangladesh-july-revolution", "kenya-gen-z"],
    relatedHistorySlugs: [],
    liveQuery: {
      strong: ["Sushila Karki", "KP Sharma Oli", "Gen Z protest", "social media ban", "Nepal uprising", "Ashok Raj Sigdel"],
      context: ["Nepal", "Kathmandu"],
      exclude: [],
    },
    analysisReviewedAt: "2026-07-22",
    predictionConfidence: "low",
    published: true,
  },
  {
    id: "india-cockroach-janta",
    slug: "india-cockroach-janta",
    title: "India's Cockroach Janta Party",
    subtitle: "Online satire over a judge's 'cockroaches' remark became a month of sit-ins at Jantar Mantar over exam leaks and jobs",
    era: "square-revolutions",
    region: "south-asia",
    country: "India",
    revoltType: "democratic-uprising",
    status: "active",
    dateDisplay: "2026 to present",
    dateStart: 2026,
    summary:
      "The Cockroach Janta Party began in May 2026 as online satire. On 15 May 2026 the Chief Justice of India, Surya Kant, compared unemployed youth to cockroaches and parasites of society, a remark he later said had referred to people entering professions on fake degrees. Abhijeet Dipke, a communications strategist, launched the Cockroach Janta Party (CJP) the next day as an online collective that embraced the insult rather than reject it, and its Instagram following grew into the millions within days. The movement held its first street protest at Jantar Mantar in New Delhi on 6 June 2026 and sustained a sit-in there for roughly a month, demanding the resignation of Union Education Minister Dharmendra Pradhan over a 2026 NEET medical-entrance paper leak and other examination failures. On 20 July 2026, the opening day of parliament's monsoon session, a Sansad Chalo march toward parliament was met with baton charges, tear gas, an internet shutdown near the building and the closure of metro stations. The movement remains active and its central demand is unmet.",
    significance:
      "The Cockroach Janta Party is a test of whether a leaderless, satire-driven online movement can convert a very large social-media following into sustained street pressure inside the world's most populous democracy. It reframed an insult from the bench into a mass identity, and turned a technical grievance, examination-paper leaks, into a national demand for a cabinet minister's resignation, without, as of the last review, extracting a concession beyond a government offer to meet two of its activists.",
    analyticalOutlook:
      "Placement on the arc: an early-stage nonviolent protest movement. It has drawn large crowds and national attention but has not produced a break in the security forces, a split in the governing party's parliamentary majority, or a concrete government concession on its central demand. The comparative record for movements at this point is mixed. Nonviolent campaigns have historically outperformed armed ones, but participation in a country of roughly 1.4 billion would need to reach tens of millions to approach the thresholds researchers associate with success, and an exam-reform grievance has no single institutional pressure point equivalent to a contested election. Where it goes next likely depends less on crowd size on any one day than on whether the movement builds a durable organization past its viral moment and whether any part of the governing coalition responds to its demands.",
    grievances: [
      { kind: "education", intensity: 90, evidence: "Protesters cite a 2026 NEET medical-entrance paper leak that, according to Al Jazeera, led about 2.2 million students to retake the exam in June 2026, alongside reported CBSE marking irregularities and a long pattern of examination failures." },
      { kind: "employment", intensity: 80, evidence: "The movement took its name from Chief Justice Surya Kant's 15 May 2026 remark comparing unemployed youth to cockroaches and parasites of society, which many young people read as dismissing high youth joblessness." },
      { kind: "accountability", intensity: 72, evidence: "The core demands are the resignation of Union Education Minister Dharmendra Pradhan, and also of Prime Minister Narendra Modi, alongside broader reform of how public examinations are conducted; the Union government made no concession on the resignation demands during the protests." },
      { kind: "repression", intensity: 62, evidence: "The 20 July 2026 march toward parliament was met with baton (lathi) charges and tear gas, an internet shutdown near parliament, prohibitory orders and the closure of five metro stations, per Wikipedia and Al Jazeera; the CJP also reported detentions, which police denied." },
    ],
    repressionLevel: "high",
    actors: [
      { actorType: "vanguard", name: "The Cockroach Janta Party", description: "An online satirical collective founded by Abhijeet Dipke on 16 May 2026 that adopted the cockroach label and built a large Instagram following before moving to the streets.", roleInArc: "Provided the name, framing and digital organizing vehicle that turned a viral joke into a protest movement.", defected: false },
      { actorType: "students-youth", name: "Student organizations at the sit-in", description: "Campus unions including the All India Students Association, the All India Students Federation and the Students Federation of India, which joined the Jantar Mantar protests.", roleInArc: "Supplied organizational continuity and turnout for the month-long sit-in and the march on parliament.", defected: false },
      { actorType: "masses", name: "Students, parents and professionals", description: "Exam aspirants and their families alongside doctors, lawyers, teachers and other members of the public who joined the protests.", roleInArc: "Broadened a single-issue exam grievance into a visible cross-section of urban discontent.", defected: false },
      { actorType: "regime", name: "The central government and Education Minister Dharmendra Pradhan", description: "The Bharatiya Janata Party-led Union government, whose education portfolio is the direct target of the resignation demand.", roleInArc: "Declined to concede the central demand, characterized the protests as politically driven, and offered to hear the activists' concerns.", defected: false },
      { actorType: "security-forces", name: "Delhi Police", description: "The city police under the Union Home Ministry, deployed in large numbers around Jantar Mantar and parliament.", roleInArc: "Enforced barricades, an internet shutdown and metro closures and dispersed the 20 July march with batons and tear gas, while denying allegations of unlawful force.", defected: false },
    ],
    tactics: [
      { tacticType: "digital-mobilization", description: "Satirical Instagram content that built a following reported by several outlets as surpassing the ruling BJP's within days of the party's launch.", prominence: "high" },
      { tacticType: "occupation", description: "A sit-in at Jantar Mantar, New Delhi, sustained for roughly a month from June 2026.", prominence: "high" },
      { tacticType: "mass-demonstration", description: "Street protests beginning on 6 June 2026 and culminating in the Sansad Chalo march toward parliament on 20 July 2026.", prominence: "high" },
      { tacticType: "civil-disobedience", description: "An indefinite hunger strike begun by activist Sonam Wangchuk on 28 June 2026, plus symbolic actions such as cockroach costumes and clean-up drives.", prominence: "medium" },
    ],
    resistanceType: "nonviolent",
    phases: [
      { phase: "old-regime-crisis", label: "Exam leaks and a remark from the bench", tStart: 0.00, tEnd: 0.12, intensity: 30, reached: true, summary: "A 2026 NEET paper leak that forced a mass re-test, alongside other examination failures, feeds anger over exam integrity and youth unemployment. A Chief Justice's remark comparing jobless youth to cockroaches becomes a flashpoint.", keyEvents: ["Reports of a 2026 NEET medical-entrance paper leak that, per Al Jazeera, led about 2.2 million students to retake the exam in June 2026", "Chief Justice Surya Kant's 15 May 2026 remark comparing unemployed youth to cockroaches and parasites, which he later said referred to people entering professions on fake degrees"] },
      { phase: "intellectual-desertion", label: "Satire flips the insult", dateStart: "2026-05-16", tStart: 0.12, tEnd: 0.22, intensity: 45, reached: true, summary: "Rather than reject the label, young people embrace it. An online collective forms around the cockroach identity and its following grows rapidly, withdrawing rhetorical legitimacy from the remark and, by extension, the establishment behind it.", keyEvents: ["Abhijeet Dipke launches the Cockroach Janta Party as an online collective on 16 May 2026", "The party's Instagram following climbs into the millions within days, which several outlets reported as surpassing the ruling BJP's"] },
      { phase: "the-spark", label: "First march on Jantar Mantar", dateStart: "2026-06-06", tStart: 0.22, tEnd: 0.34, intensity: 65, reached: true, summary: "The movement moves offline. Hundreds gather at Jantar Mantar for a first authorized protest, and the demand for the Education Minister's resignation is announced.", keyEvents: ["First street protest at Jantar Mantar, New Delhi, on 6 June 2026", "A public demand for Education Minister Dharmendra Pradhan's resignation over the exam leaks"] },
      { phase: "moderate-phase", label: "A month of sit-ins and a march on parliament", dateStart: "2026-06", tStart: 0.34, tEnd: 0.48, intensity: 76, reached: true, summary: "A sit-in holds Jantar Mantar for roughly a month around specific reform demands. A hunger strike raises the stakes, and a march toward parliament on the opening day of the monsoon session is dispersed with batons and tear gas amid an internet shutdown and metro closures.", keyEvents: ["A sit-in occupation of Jantar Mantar sustained for roughly a month", "Activist Sonam Wangchuk begins an indefinite hunger strike on 28 June 2026 and is hospitalized in mid-July", "A Sansad Chalo march toward parliament on 20 July 2026 met with baton charges, tear gas, an internet shutdown near parliament and the closure of five metro stations"] },
    ],
    outcome: "ongoing-unresolved",
    peakParticipationPct: null,
    peakParticipationDisplay:
      "Crowd estimates for the 20 July 2026 march ranged widely, from more than 10,000 reported by Al Jazeera to the organizers' claim of about 100,000. In a country of roughly 1.4 billion, even the higher figure is far below the tens of millions that the commonly cited 3.5 percent threshold would require.",
    crossedParticipationThreshold: false,
    militaryDefection: "none",
    foreignIntervention: "none",
    deathToll:
      "No protester deaths have been confirmed. After the 20 July 2026 march, hospitals reported dozens of protesters injured by baton charges and tear gas, the CJP claimed about 150 people were hospitalized, and Delhi Police reported 118 officers injured and 15 to 20 government vehicles damaged. The two sides' casualty counts differ and police denied using unlawful force.",
    deathTollLow: null,
    deathTollHigh: null,
    regimeBefore: "democracy",
    regimeAfter: "unresolved",
    democratizationDelta: null,
    successFactors: [
      { factorKey: "resistance_method", label: "Method of struggle", framework: "chenoweth", status: "Nonviolent throughout, including sit-ins, a hunger strike and marches, despite baton charges and tear gas at the July 2026 march.", direction: "favors-movement", baseRate: "About 53 percent of nonviolent campaigns from 1900 to 2006 succeeded, versus about 26 percent for armed ones.", rationale: "Staying nonviolent keeps the historically more favorable odds available and helps a movement recruit broadly across class and profession.", sources: ["Chenoweth and Stephan, Why Civil Resistance Works (2011)"], asOf: "2026-07", confidence: "medium" },
      { factorKey: "security_defection", label: "Did the security forces defect", framework: "chenoweth", status: "None reported. Delhi Police enforced barricades, closures and dispersal without any visible unit-level refusal.", direction: "favors-regime", baseRate: "Defection of the security forces is the single strongest predictor of a nonviolent campaign's success.", rationale: "Without any break in the forces policing the protests, the government has been able to contain the sit-in and the march without concessions.", sources: ["Nepstad, Nonviolent Revolutions (2011)"], asOf: "2026-07", confidence: "high" },
      { factorKey: "peak_participation", label: "Peak participation", framework: "chenoweth", status: "Large online following, but verified street turnout in the tens of thousands, far below a mass-population share in a country of roughly 1.4 billion.", direction: "favors-regime", baseRate: "No nonviolent campaign that mobilized at least 3.5 percent of the population at its peak has failed to achieve its stated aim.", rationale: "For India the 3.5 percent threshold is on the order of tens of millions of people; the largest reported crowd to date is orders of magnitude below that.", sources: ["Chenoweth and Stephan, Why Civil Resistance Works (2011)"], asOf: "2026-07", confidence: "medium" },
      { factorKey: "elite_fracture", label: "Did the ruling elite split", framework: "goldstone", status: "None visible. The governing party's parliamentary majority is intact; the support the movement has drawn comes from opposition parties already outside government.", direction: "favors-regime", baseRate: "Revolutions and forced political openings rarely succeed until the ruling elite itself fractures.", rationale: "Opposition endorsement without a crack inside the governing coalition or the administration leaves the government under little internal pressure to concede.", sources: ["Goldstone, Revolution and Rebellion in the Early Modern World (1991)"], asOf: "2026-07", confidence: "medium" },
    ],
    keyFigures: [
      { name: "Abhijeet Dipke", role: "Communications strategist who founded the Cockroach Janta Party as an online collective on 16 May 2026" },
      { name: "Dharmendra Pradhan", role: "Union Education Minister whose resignation is the movement's central demand", wikipedia: "https://en.wikipedia.org/wiki/Dharmendra_Pradhan" },
      { name: "Sonam Wangchuk", role: "Ladakhi engineer and education activist who began an indefinite hunger strike at the protest site on 28 June 2026 and was later hospitalized", born: 1966, wikipedia: "https://en.wikipedia.org/wiki/Sonam_Wangchuk_(engineer)" },
      { name: "Surya Kant", role: "Chief Justice of India whose 15 May 2026 remark comparing unemployed youth to cockroaches gave the movement its name", wikipedia: "https://en.wikipedia.org/wiki/Surya_Kant_(judge)" },
    ],
    legacyPoints: [
      "Turned a Chief Justice's 'cockroach' remark into the name and identity of a mass youth movement within days.",
      "Built one of the largest social-media followings of any Indian political formation, reported by several outlets as surpassing the ruling BJP's, faster than it built a street organization.",
      "Made examination-paper integrity, a technical administrative failure, the basis of a national demand for a cabinet minister's resignation.",
    ],
    perspectives: [
      { id: "cjp-movement", viewpoint: "The Cockroach Janta Party and allied students", viewpointType: "movement", regionOrigin: "New Delhi", narrative: "A judge called us cockroaches and parasites for being young and out of work, so we took the name. The exams that were supposed to decide our futures leaked, and millions of us sat them again. We are not asking for the government to fall. We are asking one minister to answer for a system that keeps leaking papers, and so far the answer has been barricades, batons and a cut internet.", keyArguments: ["The grievance is exam integrity and youth unemployment, not partisan politics", "Embracing the cockroach insult turned a put-down into a mass identity", "The government has answered a reform demand with policing rather than accountability"], emphasized: ["The 2026 NEET paper leak and repeated exam failures", "The scale of the online following", "Sonam Wangchuk's hunger strike"], omitted: ["The gap between the movement's online following and verified street turnout", "Its limited durable organization beyond the founding figure"], notableQuotes: [{ text: "This rotten system refuses to take action. It cannot see the pain of students.", speaker: "Jyoti Rajput, a protester", context: "Quoted by Al Jazeera at the 20 July 2026 march" }] },
      { id: "cjp-government", viewpoint: "The central government's position", viewpointType: "regime", regionOrigin: "New Delhi", narrative: "Examination reform is under way and the paper-leak cases are being handled by the courts and investigating agencies. What is playing out at Jantar Mantar is a campaign amplified by opposition parties, not a spontaneous student cause. Police acted to keep an overcrowded protest from turning dangerous, and allegations of unlawful force are denied. The government has offered to hear the protesters' concerns directly.", keyArguments: ["The exam-leak cases are being addressed through the courts and agencies", "The mobilization is politically driven by opposition parties", "Police say they acted on public-safety grounds and deny unlawful force"], emphasized: ["Existing exam-reform measures", "The opposition parties backing the protests", "An offer for two activists to meet a senior minister"], omitted: ["The internet shutdown and metro closures around parliament", "Hospital reports of injured protesters", "The absence of a government response to the resignation demand"], notableQuotes: [{ text: "acting against the nation", speaker: "Dharmendra Pradhan, Education Minister", context: "Al Jazeera reported the minister accusing the protesters in these terms during the July 2026 protests" }] },
    ],
    connections: [
      { targetSlug: "bangladesh-july-revolution", targetTitle: "Bangladesh's July Revolution", type: "shared-repertoire", description: "Both are South Asian youth movements of the 2020s that began over a specific grievance, a hiring quota in Dhaka and exam leaks in Delhi, and organized largely through social media rather than an established party structure." },
      { targetSlug: "hong-kong", targetTitle: "Hong Kong's Umbrella and 2019 Protests", type: "shared-repertoire", description: "The CJP shares the leaderless, digitally coordinated repertoire seen in Hong Kong, where organizing ran through online networks rather than a single identifiable leadership that authorities could remove." },
    ],
    media: [],
    relatedRevoltSlugs: ["bangladesh-july-revolution", "hong-kong"],
    relatedHistorySlugs: [],
    liveQuery: {
      strong: ["Cockroach Janta Party", "Cockroach Janata", "Dharmendra Pradhan", "Abhijeet Dipke", "Jantar Mantar"],
      context: ["India", "New Delhi", "Delhi"],
      exclude: ["pest control", "infestation", "extermination", "insecticide"],
    },
    analysisReviewedAt: "2026-07-22",
    predictionConfidence: "low",
    published: true,
  },
];
